services:
  # 1. Frontend - Static Site
  - type: static
    name: cloudmanager-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
    routes:
      - type: rewrite
        source: /api/*
        destination: https://erp-automation-fr03.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html

  # 2. Backend - Node Web Service
  - type: web
    name: cloudmanager-backend
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install && npx prisma generate
    startCommand: npx tsx index.ts
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dev_erp_render
          property: connectionString
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
